# Generated by Django 3.0.7 on 2020-06-18 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('product_no', models.BigIntegerField()),
                ('parts_id', models.BigIntegerField()),
                ('parts_name', models.CharField(max_length=288)),
                ('quantity', models.IntegerField()),
                ('barcode', models.CharField(max_length=288)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('purchase_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('challan_no', models.CharField(max_length=288)),
                ('challan_date', models.DateTimeField(auto_now_add=True)),
                ('supplier', models.CharField(max_length=288)),
                ('parts_id', models.BigIntegerField()),
                ('quantity', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SparePart',
            fields=[
                ('parts_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=288)),
                ('unit', models.CharField(max_length=288)),
                ('description', models.TextField(blank=True, null=True)),
                ('quantity', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('unit_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('unit_name', models.CharField(max_length=288, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
