# Generated by Django 2.2.13 on 2020-06-21 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('email_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email_name', models.CharField(max_length=288)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_no', models.BigIntegerField()),
                ('product_id', models.CharField(blank=True, max_length=288, null=True)),
                ('product_name', models.CharField(blank=True, max_length=288, null=True)),
                ('product_date', models.DateTimeField(auto_now=True)),
                ('product_quantity', models.BigIntegerField(blank=True, null=True)),
                ('product_invoice', models.CharField(blank=True, max_length=288, null=True)),
                ('product_store', models.CharField(blank=True, max_length=288, null=True)),
                ('product_comment', models.TextField(blank=True, null=True)),
                ('product_barcode', models.CharField(blank=True, max_length=288, null=True)),
                ('parts_id', models.BigIntegerField(blank=True, null=True)),
                ('parts_name', models.CharField(blank=True, max_length=288, null=True)),
                ('parts_unit', models.CharField(blank=True, max_length=288, null=True)),
                ('parts_box', models.CharField(blank=True, max_length=288, null=True)),
                ('parts_quantity', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Open Status', 'Open Status'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Open Status', max_length=50)),
                ('parts_invoice', models.CharField(blank=True, max_length=288, null=True)),
                ('parts_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('purchase_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('challan_no', models.CharField(max_length=288)),
                ('supplier', models.CharField(max_length=288)),
                ('parts_id', models.BigIntegerField()),
                ('quantity', models.BigIntegerField(blank=True, null=True)),
                ('box', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SparePart',
            fields=[
                ('parts_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=288)),
                ('unit', models.CharField(max_length=288)),
                ('description', models.TextField(blank=True, null=True)),
                ('quantity', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('unit_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('unit_name', models.CharField(max_length=288, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
