# Generated by Django 3.0.7 on 2020-06-18 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spareParts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_name',
            field=models.CharField(default=1, max_length=288),
            preserve_default=False,
        ),
    ]
