# Generated by Django 3.0.7 on 2020-06-17 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spareParts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_no',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
