# Generated by Django 2.2.13 on 2020-06-23 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spareParts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductEmailSettings',
            fields=[
                ('email_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email_name', models.CharField(max_length=288)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='emailsettings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
