# Generated by Django 3.0.7 on 2020-06-18 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spareParts', '0002_product_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='parts_unit',
            field=models.CharField(default=1, max_length=288),
            preserve_default=False,
        ),
    ]
